#!/bin/bash

set -e

script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo "---------------------------------------------------------"
echo "Building react app"

cd ${script_dir}
npm install
npm run build
cd ../

echo -e "---------------------------------------------------------"
echo -e "Symlinking build"

ln -f -s ../react/client static/react
ln -f -s ../react/client mason/react
