=head1 NAME

Shared::Genotypes - Shared functions for testing genotypes

=cut

package Shared::Genotypes;
use strict;
use warnings;
use Exporter qw(import); # Inherit the standard import routine
use LWP::UserAgent;
use JSON;

our @ISA= qw( Exporter );

# Possible exports
our @EXPORT_OK = qw( create_tissue_sample_genotypes upload_tissue_sample_genotypes $vcf_expected_accessions $vcf_expected_tissue_samples );

# Default exports
our @EXPORT = qw( create_tissue_sample_genotypes upload_tissue_sample_genotypes $vcf_expected_accessions $vcf_expected_tissue_samples );

# The expected VCF content when downloading by accession (ie. all tissue samples)
our $vcf_expected_accessions = "##INFO=<ID=VCFDownload, Description=\'VCF file for testing uploading genotypes using tissue samples\'>
##fileformat=VCFv4.0
##FORMAT=<ID=GT,Number=1,Type=String,Description=\"Genotype\">
##FORMAT=<ID=AD,Number=.,Type=Integer,Description=\"Allelic depths for the reference and alternate alleles in the order listed\">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description=\"Read Depth (only filtered reads used for calling)\">
##FORMAT=<ID=GQ,Number=1,Type=Float,Description=\"Genotype Quality\">
##FORMAT=<ID=PL,Number=3,Type=Float,Description=\"Normalized, Phred-scaled likelihoods for AA,AB,BB genotypes where A=ref and B=alt; not applicable if site is not biallelic\">
##source=FILE GENERATED BY BREEDBASE
##Genotyping protocol id(s)={tissue_sample_protocol_id}
##Genotyping protocol name(s)=Test Genotyping Protocol for Tissue Samples
##SynonymsOfAccessions=\" test_accession1=(test_accession1_synonym1)\"
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	test_accession1_leaf-1	test_accession1_leaf-2	test_accession1_leaf-3
1	10	S1_10	G	A	.	PASS	.	GT:AD:DP:GQ:PL:NT:DS	./.:0,0:0:.:1::NA	0/0:10,10:20:99:0,255,255:G,G:0	1/1:10,10:20:99:0,255,255:A,A:2
";

# The expected VCF content when downloading by select tissue examples (ie. just tissue sample #1 and #2)
our $vcf_expected_tissue_samples = "##INFO=<ID=VCFDownload, Description=\'VCF file for testing uploading genotypes using tissue samples\'>
##fileformat=VCFv4.0
##FORMAT=<ID=GT,Number=1,Type=String,Description=\"Genotype\">
##FORMAT=<ID=AD,Number=.,Type=Integer,Description=\"Allelic depths for the reference and alternate alleles in the order listed\">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description=\"Read Depth (only filtered reads used for calling)\">
##FORMAT=<ID=GQ,Number=1,Type=Float,Description=\"Genotype Quality\">
##FORMAT=<ID=PL,Number=3,Type=Float,Description=\"Normalized, Phred-scaled likelihoods for AA,AB,BB genotypes where A=ref and B=alt; not applicable if site is not biallelic\">
##source=FILE GENERATED BY BREEDBASE
##Genotyping protocol id(s)={tissue_sample_protocol_id}
##Genotyping protocol name(s)=Test Genotyping Protocol for Tissue Samples
##SynonymsOfAccessions=\" test_accession1=(test_accession1_synonym1)\"
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	test_accession1_leaf-1	test_accession1_leaf-3
1	10	S1_10	G	A	.	PASS	.	GT:AD:DP:GQ:PL:NT:DS	./.:0,0:0:.:1::NA	1/1:10,10:20:99:0,255,255:A,A:2
";

sub create_tissue_sample_genotypes {
    my ($schema) = @_;

    my $accession = 'test_accession1';
    my $num_tissue_samples = 3;
    my $location = 'Cornell Biotech';
    my $breeding_program = 'test';
    my $organism = $schema->resultset("Organism::Organism")->first();

    # Create Tissue Samples
    my $accession_id = $schema->resultset("Stock::Stock")->find({uniquename=>$accession})->stock_id();

    my $tissue_sample_cvterm_id = SGN::Model::Cvterm->get_cvterm_row($schema, 'tissue_sample', 'stock_type')->cvterm_id();
    my $tissue_type_cvterm_id = SGN::Model::Cvterm->get_cvterm_row($schema, 'tissue_type', 'stock_property')->cvterm_id();
    my $tissue_sample_of_cvterm_id = SGN::Model::Cvterm->get_cvterm_row($schema, 'tissue_sample_of', 'stock_relationship')->cvterm_id();

    my $location_rs = $schema->resultset('NaturalDiversity::NdGeolocation')->search({description => $location});
    my $location_id = $location_rs->first->nd_geolocation_id;

    my $bp_rs = $schema->resultset('Project::Project')->search({name => $breeding_program});
    my $breeding_program_id = $bp_rs->first->project_id;

    my @tissue_samples;

    foreach my $i (1 .. $num_tissue_samples) {
        # Create tissue sample stocks
        my $tissue_sample_name = $accession . "_leaf-" . ${i};
        my $tissue_sample = $schema->resultset("Stock::Stock")->find_or_create({
            uniquename => $tissue_sample_name,
            name => $tissue_sample_name,
            type_id => $tissue_sample_cvterm_id,
            organism_id => $organism->organism_id,
        });
        # Create tissue sample stock properties
        $schema->resultset("Stock::Stockprop")->find_or_create( {
            stock_id => $tissue_sample->stock_id(),
            type_id => $tissue_type_cvterm_id,
            value => "leaf",
        });
        # Create tissue sample stock relationships
        $schema->resultset("Stock::StockRelationship")->find_or_create({
            subject_id => $tissue_sample->stock_id(),
            object_id => $accession_id,
            type_id => $tissue_sample_of_cvterm_id,
        });
        push(@tissue_samples, $tissue_sample_name);
    }

    # Create VCF File for Genotyping Data
    my $upload_tissue_sample_genotypes = '##INFO=<ID=VCFDownload, Description=\'VCF file for testing uploading genotypes using tissue samples\'>
    ##fileformat=VCFv4.0
    ##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
    ##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the reference and alternate alleles in the order listed">
    ##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth (only filtered reads used for calling)">
    ##FORMAT=<ID=GQ,Number=1,Type=Float,Description="Genotype Quality">
    ##FORMAT=<ID=PL,Number=3,Type=Float,Description="Normalized, Phred-scaled likelihoods for AA,AB,BB genotypes where A=ref and B=alt; not applicable if site is not biallelic">
    #CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	test_accession1_leaf-1	test_accession1_leaf-2	test_accession1_leaf-3
    1 	10 	S1_10	G	A	.	PASS	.	GT:AD:DP:GQ:PL	./.:0,0:0:.:1	0/0:10,10:20:99:0,255,255	1/1:10,10:20:99:0,255,255
    ';
    $upload_tissue_sample_genotypes =~ s/^\s+//gm;

    my $upload_tissue_sample_genotypes_path = "/tmp/upload_tissue_sample_genotypes.vcf";
    open(my $fh_vcf, '>', $upload_tissue_sample_genotypes_path) or die $!;
    print $fh_vcf $upload_tissue_sample_genotypes;
    close($fh_vcf);

    return $upload_tissue_sample_genotypes_path;
}

sub upload_tissue_sample_genotypes {
    my ($schema, $mech, $upload_tissue_sample_genotypes_path) = @_;

    my $accession = 'test_accession1';
    my $num_tissue_samples = 3;
    my $location = 'Cornell Biotech';
    my $breeding_program = 'test';
    my $organism = $schema->resultset("Organism::Organism")->first();

    my $location_rs = $schema->resultset('NaturalDiversity::NdGeolocation')->search({description => $location});
    my $location_id = $location_rs->first->nd_geolocation_id;

    my $bp_rs = $schema->resultset('Project::Project')->search({name => $breeding_program});
    my $breeding_program_id = $bp_rs->first->project_id;

    # Get a sgn_session_id for creating a genotyping protocol and project
    $mech->post_ok('http://localhost:3010/brapi/v1/token', [ "username" => "janedoe", "password" => "secretpw", "grant_type" => "password" ]);
    my $response = decode_json $mech->content;
    my $sgn_session_id = $response->{access_token};

    # this upload simultaneous creates a genotyping project and a genotyping protocol
    my $ua = LWP::UserAgent->new;
    $response = $ua->post(
        'http://localhost:3010/ajax/genotype/upload',
        Content_Type => 'form-data',
        Content => [
            upload_genotype_vcf_file_input => [ $upload_tissue_sample_genotypes_path, 'genotype_vcf_data_upload' ],
            "sgn_session_id"=>$sgn_session_id,
            "upload_genotypes_species_name_input"=>$organism->species(),
            "upload_genotype_vcf_project_name"=>"Tissue Sample Genotype Test",
            "upload_genotype_location_select"=>$location_id,
            "upload_genotype_year_select"=>"2026",
            "upload_genotype_breeding_program_select"=>$breeding_program_id,
            "upload_genotype_vcf_observation_type"=>"tissue_sample", #IDEALLY THIS IS "tissue_sample"
            "upload_genotype_vcf_facility_select"=>"IGD",
            "upload_genotype_vcf_project_description"=>"Test uploading genotypes to tissue samples",
            "upload_genotype_vcf_protocol_name"=>"Test Genotyping Protocol for Tissue Samples",
            "upload_genotype_vcf_include_igd_numbers"=>0,
            "upload_genotype_vcf_reference_genome_name"=>"Test_Reference_v1",
            "upload_genotype_add_new_accessions"=>0,
        ]
    );

    return $response
}